name: "nightly build-jdk nightly"
on:
  push:

jobs:
  hotspot14:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, macos-10.15, windows-2016]
        version: [8, 11, 15]
    steps:
    - uses: actions/checkout@v1
    - uses: eclipse/build-openj9@v1
      id: buildJDK
      with: 
        version: ${{ matrix.version}}
    - run: ${{ steps.buildJDK.outputs.BuildJDKDir }}/bin/java -version