name: "run-aqa build with push to master"
on:
  push:


jobs:
  installJDK: # make sure build/ci work properly
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] #[ubuntu-latest, macos-latest, windows-2016]
    steps:
    - uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: '15'
        targets: 'JDK_15'
        impl: 'openj9'
        source: 'nightly'
        #source: 'https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u-2020-12-02-12-32/OpenJDK8U-jdk_x64_linux_hotspot_2020-12-02-12-32.tar.gz'
        #sourceType: 'url'
    - name: AQA
      uses: sophia-guo/run-aqa@lists
      with: 
        version: '15'
        jdksource: 'install-jdk'
        build_list: 'functional/cmdLineTests,functional/cmdline_options_testresources'
        target: '_testSCCMLTests1_openj9'